### ISSUE TITLE
Topic parameter example displayed wrong

### ISSUE THREAD

**Issue by AtosNicoS** [asyncapi/docgen#31]
```yaml
topics:
  event.teltonika.{serial}.mobile.bytes_received:
    parameters:
      - name: "serial"
        description: "Serial number of the router. Serial number can be taken from the device or via the command: `uci get hwinfo.hwinfo.serial`."
        schema:
          type: "string"
          title: "Serial number"
          description: "Serial number, usually 8 digests long."
          example: "01234567"
```

The example is not shown/empty :(
![grafik](https://user-images.githubusercontent.com/37442184/42943111-36bfefba-8b62-11e8-8454-586250ff185c.png)

**Comment by AtosNicoS** [comment]
It seems to also happen for the payload. Here one working example is listed and the other is also a single gray line:

```yaml
      payload:
        title: "Bytes"
        description: "Received data in bytes. Encoded as UTF-8 string"
        type: "string"
        minimum: 0
        example: "67"
```

![grafik](https://user-images.githubusercontent.com/37442184/42986046-5b8aa618-8bf4-11e8-8936-0236387836f5.png)
