### ISSUE TITLE
Support for listing array items 

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/docgen#6]
Because (I think) of the way nested properties are output, the content (`items`) of arrays are not expanded. Unsure if this is by design or not?

**Comment by fmvilas** [comment]
Not sure I understand what you mean :)

**Comment by MikeRalphson** [comment]
Only `properties` and directly-nested `properties` of schema objects are output by asyncapi-docgen. If a schema has two properties:

```yaml
test1:
  type: object
  properties:
    first:
      type: string
    second:
      type: string
test2:
  type: array
  items:
    type: object
    properties:
      third:
        type: string
      fourth:
        type: string
```

the properties under `test.properties` are included, but the properties under `test2.items` are not listed, only the single property `test2` with type `array`.

![image](https://user-images.githubusercontent.com/21603/28824211-fa3de920-76b8-11e7-97e5-a9521313602d.png)
